/**
 * Contract: Analysis Screen Composable Interface
 * 
 * Purpose: Defines the contract for Analysis screen UI components and interactions
 * Author: Generated by /speckit.plan
 * Date: 2025-10-26
 */

package com.tiarkaerell.ibstracker.ui.screens

import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import com.tiarkaerell.ibstracker.data.model.*
import com.tiarkaerell.ibstracker.ui.viewmodel.AnalysisAction
import com.tiarkaerell.ibstracker.ui.viewmodel.AnalysisTab
import com.tiarkaerell.ibstracker.ui.viewmodel.AnalysisUiState
import com.tiarkaerell.ibstracker.ui.viewmodel.FilterEvent

/**
 * Main Analysis screen composable contract
 * 
 * Displays symptom-trigger correlations with filtering and detailed views.
 * Implements Material Design 3 with accessibility support.
 */
@Composable
fun AnalysisScreen(
    uiState: AnalysisUiState,
    analysisResult: AnalysisResult?,
    filters: AnalysisFilters,
    onAction: (AnalysisAction) -> Unit,
    onFilterChange: (FilterEvent) -> Unit,
    modifier: Modifier = Modifier
)

/**
 * Expandable symptom card showing trigger probabilities
 * 
 * Key features:
 * - Material Design 3 card with smooth animations
 * - Color-coded severity indicators
 * - Accessibility-compliant touch targets (48dp minimum)
 * - Progress bars for probability visualization
 */
@Composable
fun SymptomCard(
    symptom: SymptomAnalysis,
    isExpanded: Boolean,
    onToggleExpanded: () -> Unit,
    onTriggerSelected: (String) -> Unit,
    modifier: Modifier = Modifier
)

/**
 * Individual trigger probability display within symptom card
 * 
 * Shows:
 * - Food name and category
 * - Probability percentage with progress bar
 * - Color coding based on probability level
 * - Confidence indicator
 */
@Composable
fun TriggerProbabilityItem(
    trigger: TriggerProbability,
    onTriggerSelected: () -> Unit,
    modifier: Modifier = Modifier
)

/**
 * Visual progress bar for probability display
 * 
 * Features:
 * - Color coding: Red (>70%), Orange (40-70%), Green (<40%)
 * - Rounded corners for Material Design 3
 * - Smooth animations for value changes
 * - Accessible labels and descriptions
 */
@Composable
fun ProbabilityProgressBar(
    probability: Double, // 0.0 to 1.0
    confidence: Double,  // 0.0 to 1.0
    modifier: Modifier = Modifier
)

/**
 * Filter chips row for analysis customization
 * 
 * Includes:
 * - Date range selection (Last 7/30/90 days, Custom, All time)
 * - Severity threshold filter
 * - Symptom type toggles
 * - Food category filters
 * - Clear all filters action
 */
@Composable
fun AnalysisFilterChips(
    filters: AnalysisFilters,
    availableSymptoms: List<String>,
    onFilterChange: (FilterEvent) -> Unit,
    modifier: Modifier = Modifier
)

/**
 * Date range picker dialog
 * 
 * Material Design 3 date picker with:
 * - Quick select options (7/30/90 days)
 * - Custom date range picker
 * - Validation for valid date ranges
 */
@Composable
fun DateRangePickerDialog(
    currentRange: DateRange,
    onRangeSelected: (DateRange) -> Unit,
    onDismiss: () -> Unit
)

/**
 * Severity filter slider
 * 
 * Features:
 * - Material Design 3 slider component
 * - Range from 1-10 with "Any" option
 * - Visual indicators for severity levels
 * - Haptic feedback on value changes
 */
@Composable
fun SeverityFilterSlider(
    currentThreshold: Int?,
    onThresholdChanged: (Int?) -> Unit,
    modifier: Modifier = Modifier
)

/**
 * Insights tab showing plain-language analysis
 * 
 * Displays:
 * - Key patterns in user-friendly language
 * - Recommendations based on analysis
 * - Statistical summaries
 * - Confidence indicators
 */
@Composable
fun InsightsTab(
    analysisResult: AnalysisResult,
    modifier: Modifier = Modifier
)

/**
 * Patterns tab showing recurring correlations
 * 
 * Features:
 * - Pattern type indicators
 * - Strength and frequency metrics
 * - Related foods and symptoms
 * - Visual pattern representations
 */
@Composable
fun PatternsTab(
    patterns: List<SymptomPattern>,
    onPatternSelected: (String) -> Unit,
    modifier: Modifier = Modifier
)

/**
 * Empty state when no analysis data available
 * 
 * Shows:
 * - Helpful message explaining requirements
 * - Guidance on tracking more data
 * - Quick actions to add symptoms/foods
 */
@Composable
fun AnalysisEmptyState(
    onAddSymptom: () -> Unit,
    onAddFood: () -> Unit,
    modifier: Modifier = Modifier
)

/**
 * Loading state with progress indicators
 * 
 * Features:
 * - Material Design 3 progress indicators
 * - Loading message with context
 * - Estimated completion time if available
 */
@Composable
fun AnalysisLoadingState(
    loadingMessage: String = "Analyzing correlations...",
    modifier: Modifier = Modifier
)

/**
 * Error state with retry options
 * 
 * Displays:
 * - Error message with context
 * - Retry action button
 * - Alternative actions if applicable
 */
@Composable
fun AnalysisErrorState(
    errorMessage: String,
    onRetry: () -> Unit,
    onDismiss: () -> Unit,
    modifier: Modifier = Modifier
)

/**
 * Severity indicator icon with color coding
 * 
 * Visual indicator for symptom severity levels:
 * - High: Red warning icon
 * - Medium: Orange info icon  
 * - Low: Green check icon
 */
@Composable
fun SeverityIndicator(
    severity: SeverityLevel,
    size: SeverityIndicatorSize = SeverityIndicatorSize.MEDIUM,
    modifier: Modifier = Modifier
)

enum class SeverityIndicatorSize {
    SMALL, MEDIUM, LARGE
}

/**
 * Food category chip with icon
 * 
 * Displays food category with:
 * - Category-specific icon
 * - Color coding for trigger potential
 * - Tooltip with category description
 */
@Composable
fun FoodCategoryChip(
    category: FoodCategory,
    isSelected: Boolean,
    onToggle: () -> Unit,
    modifier: Modifier = Modifier
)

/**
 * Analysis summary card for sharing
 * 
 * Compact summary showing:
 * - Top triggers with probabilities
 * - Key insights
 * - Analysis period and confidence
 * - Shareable format
 */
@Composable
fun AnalysisSummaryCard(
    analysisResult: AnalysisResult,
    onShare: () -> Unit,
    modifier: Modifier = Modifier
)

/**
 * Trigger details dialog
 * 
 * Detailed view showing:
 * - Complete trigger information
 * - Recent correlation evidence
 * - Statistical confidence metrics
 * - Recommendations for this trigger
 */
@Composable
fun TriggerDetailsDialog(
    triggerDetails: TriggerDetails,
    onDismiss: () -> Unit,
    onFoodRecategorize: (FoodCategory) -> Unit
)

/**
 * Tab navigation for analysis sections
 * 
 * Material Design 3 tab row with:
 * - Symptoms, Patterns, Insights tabs
 * - Smooth tab indicator animations
 * - Badge indicators for new insights
 */
@Composable
fun AnalysisTabRow(
    selectedTab: AnalysisTab,
    onTabSelected: (AnalysisTab) -> Unit,
    modifier: Modifier = Modifier
)

/**
 * Quick action floating action button
 * 
 * Context-sensitive FAB for:
 * - Refresh analysis
 * - Share results
 * - Export data
 */
@Composable
fun AnalysisQuickActions(
    uiState: AnalysisUiState,
    onRefresh: () -> Unit,
    onShare: () -> Unit,
    modifier: Modifier = Modifier
)